### ISSUE TITLE
Build VM as 2 steps instead of one

### ISSUE THREAD

**Issue by kikitux** [cloudfoundry/warden-test-infrastructure#8]
Hello,

First of all, thanks for sharing this.. I really did enjoy checking the Makefile you did.

I took this one step further, and I did a 2 step process, that is:

iso -> virtualbox-iso -> minimal vm -> virtualbox-ovf -> final vm
iso -> vmware-iso -> minimal vm -> vmware-vmx -> final vm

https://github.com/kikitux/packer-vagrant-oracle/tree/master/packer-make

This cut the time for each box, and allow have multiple machines that share the base minimal one.

Not sure if it's something you will like to reuse, just sharing as a token of appreciation as you did share yours first.

Thanks!
Alvaro

**Comment by zrob** [comment]
Hey @kikitux 

Thanks for sharing your findings, it looks like a pretty cool optimization.  However, we're  planning to move over to [garden](https://github.com/cloudfoundry-incubator/garden) in place of warden in the semi-near future.  Because of that we are minimizing the changes we make to warden.

Hopefully we continue to see you in the cloudfoundry community!

Thanks,
@zrob & @utako
